### ISSUE TITLE
Starry Knight does not work.

### ISSUE THREAD

**Issue by ghost** [burtlo/metro#14]
Hi, I installed metro and downloaded the starry-knight demo (https://github.com/burtlo/starry-knight). Then, i run it and correctly initiates the menu scene, but when I press 'Start game', the application closes and jumps the following error:

```
$ metro
C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/lib/metro/models/ui/space.rb:122:in `clean_up': undefined method `rehash_static' for #<CP::Space:0x614cca0> (NoMethodError)
        from C:/Documents and Settings/Robinson/Desktop/starry-knight/scenes/main_scene.rb:54:in `update'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/lib/metro/scene.rb:377:in `base_update'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/lib/metro/window.rb:41:in `update'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/lib/metro/game.rb:18:in `start!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/lib/metro.rb:108:in `start_game'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/lib/metro.rb:100:in `run'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/metro-0.3.6/bin/metro:15:in `<top (required)>'
        from C:/Ruby193/bin/metro:23:in `load'
        from C:/Ruby193/bin/metro:23:in `<main>'
```

What could cause this error? I have to clarify that a clean template made with "metro new gamename" works properly and smoothly. I using Ruby 1.9.3 on Windows. I had to manually install Gosu 0.8 because metro seems to not work with versions 0.9 and 0.10.

**Comment by shawn42** [comment]
I believe `rehash_static` was removed in the latest version of chipmunk. Try adding chipmunk 5.3.4.5 to your Gemfile to confirm.
